export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const SHOW_HIDE_CART = 'SHOW_HIDE_CART';
export const INCREASE_CART = 'INCREASE_CART';
export const DECREASE_CART = 'DECREASE_CART';